name = "camo"
main = "build/index.js"
compatibility_date = "2025-12-27"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release --features worker"

[vars]
CAMO_MAX_SIZE = "5242880"